from bloghandler import BlogHandler
from blogfront import BlogFront
from postpage import PostPage
from newpost import NewPost
from signup import Signup
from register import Register
from login import Login
from logout import Logout
from blogwelcome import BlogWelcome
from editpost import EditPost
from deletepost import DeletePost
from completed import Completed
from failed import Failed
from like import Like
from deletecomment import DeleteComment
from editcomment import EditComment
